import { Server, Socket } from 'socket.io';
import Application from '../models/Application'; 
import { evaluateAndContinue } from '../services/aiService';

export const setupInterviewSocket = (io: Server) => {
  io.on('connection', (socket: Socket) => {
    
    // 1. Join Interview Room
    socket.on('join_interview', async (applicationId: string) => {
      try {
        socket.join(applicationId);
        (socket as any).applicationId = applicationId; 

        // Update status to 'In-Progress' when user enters the room
        await Application.findByIdAndUpdate(applicationId, { status: 'In-Progress' });
        console.log(`📡 User joined interview: ${applicationId}`);
      } catch (err) {
        console.error("Error joining interview room:", err);
      }
    });

    /**
     * 2. The Core AI Interview Loop
     * This handles receiving an answer, scoring it, and getting the next question.
     */
    socket.on('send_answer', async (data: { applicationId: string; answer: string }) => {
      const { applicationId, answer } = data;

      try {
        // Fetch application and populate Job Description for AI context
        const app = await Application.findById(applicationId).populate('jobId');
        if (!app) {
          return socket.emit('error', { message: "Application session not found." });
        }

        // Identify the current question (the last one in the array)
        const currentInteraction = app.interviewData[app.interviewData.length - 1];
        
        // Notify frontend that AI is processing
        socket.emit('ai_thinking');

        // Call Gemini Service
        const result = await evaluateAndContinue(
          currentInteraction.question,
          answer,
          (app.jobId as any).description,
          app.interviewData.length
        );

        // Update current interaction with user's answer and AI evaluation
        currentInteraction.answer = answer;
        currentInteraction.evaluation = result.feedback;
        currentInteraction.score = result.score;

        // Check if the AI has decided the interview is over
        if (result.nextQuestion === 'COMPLETED' || app.interviewData.length >= 5) {
          app.status = 'Completed';
          
          // Calculate Final Average Score
          const totalScore = app.interviewData.reduce((acc, curr) => acc + (curr.score || 0), 0);
          app.finalScore = Number((totalScore / app.interviewData.length).toFixed(2));

          await app.save();

          // Send final signal to Frontend
          socket.emit('interview_completed', { 
            finalScore: app.finalScore,
            message: "Interview successfully completed! Generating your results..." 
          });
          console.log(`✅ Interview Finalized: ${applicationId} | Final Score: ${app.finalScore}`);
        } else {
          // Push the next question generated by Gemini
          app.interviewData.push({
            question: result.nextQuestion,
            answer: '',
            evaluation: '',
            score: 0
          } as any);

          await app.save();

          // Send the next question to the frontend
          socket.emit('next_question', { 
            question: result.nextQuestion,
            feedback: result.feedback // Send feedback of the previous answer
          });
        }
      } catch (error) {
        console.error("Interview Loop Error:", error);
        socket.emit('error', { message: "AI failed to process. Try repeating your answer." });
      }
    });

    // 3. Voluntary Exit
    socket.on('leave_interview', async () => {
      const appId = (socket as any).applicationId;
      if (appId) {
        const app = await Application.findById(appId);
        // Only mark abandoned if it wasn't already finished
        if (app && app.status !== 'Completed') {
          await Application.findByIdAndUpdate(appId, { status: 'Abandoned' });
          console.log(`⚠️ User clicked Exit: ${appId}`);
        }
        socket.disconnect(); 
      }
    });

    // 4. Unexpected Disconnect (Internet/Tab Close)
    socket.on('disconnect', async () => {
      const appId = (socket as any).applicationId;
      if (appId) {
        const app = await Application.findById(appId);
        if (app && app.status !== 'Completed' && app.status !== 'Abandoned') {
          await Application.findByIdAndUpdate(appId, { status: 'Abandoned' });
          console.log(`❌ Connection Lost: ${appId}`);
        }
      }
    });
  });
};